name: todo_shp_loc_cubit
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  flutter_slidable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/translations/
 
